### ISSUE TITLE
frq 2 step tracker

### ISSUE THREAD

**Issue by AadyaDaita** [AadyaDaita/apcsa_java_repo#2]
### **Hacks**
- [x] Build tester method (public static void main) for Person Pojo. Test zero argument and all argument constructor. build toString method to display attributes of the class.
![image](https://user-images.githubusercontent.com/89221238/204042954-72c8b387-f412-4da6-aaf4-492b487ef70a.png)
- [x] Build **other attributes** into POJO that where mentioned in project dialog at the beginning of this blog. **Add 1 or more APIs**. Use Issues to plan and track work
  - Added another parameter to the all args constructor:
   ![image](https://user-images.githubusercontent.com/89221238/204043059-bd29609e-7405-4d4e-a92a-736cad560b8e.png)
  - Added more attributes to Person:
  ![image](https://user-images.githubusercontent.com/89221238/204042869-f223f759-35d0-4cfd-b606-d9227cdcca62.png)
  - toString API with endpoint:
  ![image](https://user-images.githubusercontent.com/89221238/204043263-3bd3e1f0-a0d3-4732-bce2-0b724ad79d29.png)
  ![image](https://user-images.githubusercontent.com/89221238/204044201-634f7661-5ecb-42b5-a7e1-604e0fb635ff.png)
- [x] Correct the BUG in setStats! Currently, it won't let you do more than one date.  (fix the endpoint part)
![image](https://user-images.githubusercontent.com/89221238/204206555-87032e4c-3aad-4308-9ef9-229f8d9b12c2.png)
![image](https://user-images.githubusercontent.com/89221238/204206470-6996b51a-70db-4629-beff-06ea861a8474.png)

### **Extra**
- [x] PBL/SQL Relationships. In POJOs you can define a relationship in SQL, the POJO Person and a POJO Day can be built to contain relationships (alternate to HashMap style). List is the interface and ArrayList is the implementation.
  - [x] Built my own StepTracker pojo
    - [x] [Step.java](https://github.com/AadyaDaita/apcsa_java_repo/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/StepTracker/Step.java)
    - [x] [StepTracker.java](https://github.com/AadyaDaita/apcsa_java_repo/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/StepTracker/StepTracker.java)
    - [x] [StepTracker Api Controller](https://github.com/AadyaDaita/apcsa_java_repo/blob/master/src/main/java/com/nighthawk/spring_portfolio/mvc/StepTracker/StepTrackerApiController.java)
![image](https://user-images.githubusercontent.com/89221238/204049828-66cb3d18-befa-43ef-9b6f-7dc4598a1de8.png)
![image](https://user-images.githubusercontent.com/89221238/204049870-a1212fcd-7742-42fe-af83-01095230089d.png)

**Comment by rebecca-123** [comment]
Score: 3/3

- All hacks completed
- Extra: StepTracker FRQ, StepTracker POJO with addDailySteps endpoint
